name: Build, Push, and Deploy User Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    
    env:
      AZURE_RG: finzen-rg
      ACR_SERVER: finzenacr.azurecr.io
      CA_NAME: finzen-api-users
      IMAGE_REPO: api-users
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Package with Maven
        run: mvn clean package
      
      - name: 1. Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 2. ACR Build and Push
        uses: azure/acr-build-push@v6
        with:
          context: .
          file: Dockerfile
          registry: ${{ env.ACR_SERVER }}
          repository: ${{ env.IMAGE_REPO }}
          tags: latest

      - name: 3. Deploy/Update Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          container-app-name: ${{ env.CA_NAME }}
          resource-group: ${{ env.AZURE_RG }}
          image: ${{ env.ACR_SERVER }}/${{ env.IMAGE_REPO }}:latest 
          
      - name: Deployment Success
        run: echo "Microservicio de Usuarios desplegado exitosamente."
